[package]
name = "ferromic"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
tokio = { version = "1.28", features = ["full"] }
flate2 = "1.0"
anyhow = "1.0"
rayon = "1.7"
indicatif = "0.17"
human_bytes = "0.4"
sysinfo = "0.28.2"
log = "0.4"
env_logger = "0.10"
num_cpus = "1.15"
crossbeam-channel = "0.5"
memmap2 = "0.5"
thiserror = "1.0"
colored = "2.0"
itertools = "0.10"
rust-htslib = "0.40"
rand = "0.8.5"
parking_lot = "0.12.1"
tempfile = "3.5"
itertools = "0.10"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'

[[bin]]
name = "ferromic"
path = "src/main.rs"

[[bin]]
name = "vcf_merge"
path = "src/merge.rs"

[[bin]]
name = "vcf_stats"
path = "src/stats.rs"
