"""Which test of "recurrence beyond architecture" is actually calibrated?

Reviewer 3 asks whether the recurrent-vs-single contrasts survive controlling for
genomic architecture. The controls in stats/recurrence_architecture_controls.py
answer with two tests, and neither targets the null cleanly:

  * covariate-adjusted regression trusts an asymptotic variance formula and a
    linear functional form for the covariates; if the form is wrong, confounding
    leaks into the recurrence coefficient and the p-value is optimistic.
  * 1:1 nearest-neighbour matching avoids that assumption but deletes 44 of 62
    loci, so it answers the question on a subsample chosen for matchability.

The null actually in dispute is conditional independence,

    H0:  outcome  _||_  recurrence  |  architecture

so the reference distribution should be built by re-randomizing RECURRENCE given
architecture, holding the outcomes fixed. The adjusted coefficient is then just a
statistic; its null comes from the randomization, not from a variance formula.
Two such tests are implemented:

  stratified permutation   permute recurrence labels within propensity-score
                           strata. No outcome model and no propensity
                           functional form is trusted beyond the strata.
  conditional randomization  redraw labels from Bernoulli(propensity) per locus
                           (Candes et al. style). Uses the propensity more
                           efficiently; valid if that model is adequate.

Calibration is MEASURED, not asserted. Null data are generated by drawing
synthetic recurrence labels from the fitted propensity while leaving the real
outcomes untouched, so outcome and recurrence are confounded through architecture
exactly as in the real data but conditionally independent by construction. A
valid test rejects 5% of the time. Power is then measured by adding a known
recurrence effect on top of the same design.

Outputs: data/recurrence_controls_calibration.tsv
         data/recurrence_controls_calibration.pdf / .png
"""
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

_HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(os.path.dirname(_HERE), "data")
IN_TSV = os.path.join(DATA, "recurrence_controls_covariates.tsv")
OUT_TSV = os.path.join(DATA, "recurrence_controls_calibration.tsv")
OUT_PDF = os.path.join(DATA, "recurrence_controls_calibration.pdf")

RNG = np.random.default_rng(20260817)
N_NULL = 1000      # null datasets used to measure type I error
N_POWER = 1000     # datasets with a planted effect, for power
N_RAND = 999       # randomizations inside each randomization test
N_STRATA = 5
ALPHA = 0.05


def _z(v):
    v = np.asarray(v, float)
    s = np.nanstd(v)
    return (v - np.nanmean(v)) / (s if s > 0 else 1.0)


def load():
    d = pd.read_csv(IN_TSV, sep="\t")
    pi_all = np.r_[d["pi_direct"].to_numpy(float), d["pi_inverted"].to_numpy(float)]
    pos = pi_all[np.isfinite(pi_all) & (pi_all > 0)]
    eps = 0.5 * np.percentile(pos, 1) if pos.size else 1e-9
    d["dlogpi"] = (np.log(d["pi_inverted"].astype(float) + eps)
                   - np.log(d["pi_direct"].astype(float) + eps))
    Z = np.column_stack([
        _z(np.log(d["size_kbp"].clip(lower=1e-6))),
        _z(d["inv_af"]),
        _z(np.log1p(d["snp_density"])),
        _z(np.log1p(d["cds_density"])),
        _z(np.log1p(d["recomb_cM_per_Mb_flank"])),
        _z(d["rel_arm_position"]),
    ])
    ok = np.isfinite(Z).all(axis=1)
    return d.loc[ok].reset_index(drop=True), Z[ok]


def logistic_propensity(Z, r, ridge=1.0, iters=100):
    """Ridge-penalised logistic fit; 62 loci and 6 covariates separate easily."""
    X = np.column_stack([np.ones(len(r)), Z])
    b = np.zeros(X.shape[1])
    pen = ridge * np.eye(X.shape[1])
    pen[0, 0] = 0.0
    for _ in range(iters):
        eta = np.clip(X @ b, -30, 30)
        p = 1.0 / (1.0 + np.exp(-eta))
        W = np.clip(p * (1 - p), 1e-6, None)
        g = X.T @ (r - p) - pen @ b
        H = X.T @ (X * W[:, None]) + pen
        step = np.linalg.solve(H, g)
        b += step
        if np.max(np.abs(step)) < 1e-9:
            break
    eta = np.clip(X @ b, -30, 30)
    return np.clip(1.0 / (1.0 + np.exp(-eta)), 0.02, 0.98)


def residual_maker(Z):
    """M = I - Z(Z'Z)^-1 Z', with intercept. Statistic uses Frisch-Waugh."""
    X = np.column_stack([np.ones(Z.shape[0]), Z])
    M = np.eye(X.shape[0]) - X @ np.linalg.pinv(X.T @ X) @ X.T
    return M


def coef_batch(R, M, y):
    """Adjusted recurrence coefficient for each row of R (n_draws x n)."""
    My = M @ y
    MR = R @ M
    num = R @ My
    den = np.einsum("ij,ij->i", R, MR)
    den = np.where(np.abs(den) < 1e-12, np.nan, den)
    return num / den


def p_randomization(r, R_null, M, y):
    obs = coef_batch(r[None, :], M, y)[0]
    null = coef_batch(R_null, M, y)
    null = null[np.isfinite(null)]
    if null.size == 0 or not np.isfinite(obs):
        return np.nan
    return (np.count_nonzero(np.abs(null) >= abs(obs)) + 1) / (null.size + 1)


def draw_stratified(r, ps, n_draw, rng):
    """Permute labels within propensity strata."""
    order = np.argsort(ps)
    strata = np.array_split(order, N_STRATA)
    out = np.tile(r.astype(float), (n_draw, 1))
    for idx in strata:
        if idx.size < 2:
            continue
        block = out[:, idx]
        for k in range(n_draw):
            block[k] = rng.permutation(block[k])
        out[:, idx] = block
    return out


def draw_crt(ps, n_draw, rng):
    return (rng.random((n_draw, ps.size)) < ps[None, :]).astype(float)


def p_hc3(r, Z, y):
    """The currently reported test, measured here rather than trusted."""
    X = np.column_stack([np.ones(len(r)), r, Z])
    XtXi = np.linalg.pinv(X.T @ X)
    b = XtXi @ X.T @ y
    e = y - X @ b
    h = np.einsum("ij,jk,ik->i", X, XtXi, X)
    om = (e / np.clip(1 - h, 1e-8, None)) ** 2
    V = XtXi @ (X.T * om) @ X @ XtXi
    se = np.sqrt(max(V[1, 1], 1e-30))
    from scipy import stats as _s
    return float(2 * _s.norm.sf(abs(b[1] / se))), float(b[1])


def p_matched(r, Z, y, rng):
    """1:1 nearest-neighbour match on architecture, then sign-flip on pairs."""
    rec = np.flatnonzero(r == 1)
    sin = np.flatnonzero(r == 0)
    if rec.size == 0 or sin.size == 0:
        return np.nan
    C = np.cov(Z, rowvar=False) + 1e-6 * np.eye(Z.shape[1])
    Ci = np.linalg.pinv(C)
    D = np.empty((rec.size, sin.size))
    for a, i in enumerate(rec):
        d = Z[sin] - Z[i]
        D[a] = np.einsum("ij,jk,ik->i", d, Ci, d)
    pairs = []
    used = set()
    for a in np.argsort(D.min(axis=1)):
        cand = [b for b in np.argsort(D[a]) if b not in used]
        if not cand:
            continue
        used.add(cand[0])
        pairs.append((rec[a], sin[cand[0]]))
    if len(pairs) < 3:
        return np.nan
    diff = np.array([y[i] - y[j] for i, j in pairs])
    obs = abs(diff.mean())
    signs = rng.choice([-1.0, 1.0], size=(N_RAND, diff.size))
    null = np.abs(signs @ diff / diff.size)
    return (np.count_nonzero(null >= obs) + 1) / (N_RAND + 1)


OUTCOMES = [("orientation-by-recurrence effect on nucleotide diversity", "dlogpi"),
            ("difference in FST", "fst"),
            ("difference in net divergence da", "da")]

METHODS = ["covariate-adjusted regression (asymptotic)",
           "matched pairs, sign-flip",
           "stratified permutation",
           "conditional randomization"]


def run():
    d, Z = load()
    r = d["recur"].to_numpy(float)
    M = residual_maker(Z)
    ps = logistic_propensity(Z, r)
    print(f"{len(d)} loci ({int(r.sum())} recurrent, {int((1-r).sum())} single-event); "
          f"propensity range {ps.min():.2f}-{ps.max():.2f}")

    rows = []
    for label, col in OUTCOMES:
        y = d[col].to_numpy(float)
        keep = np.isfinite(y)
        yk, rk, Zk, psk = y[keep], r[keep], Z[keep], ps[keep]
        Mk = residual_maker(Zk)
        obs_coef = coef_batch(rk[None, :], Mk, yk)[0]

        # ---- observed p-values on the real data
        obs_p = {}
        obs_p[METHODS[0]] = p_hc3(rk, Zk, yk)[0]
        obs_p[METHODS[1]] = p_matched(rk, Zk, yk, RNG)
        obs_p[METHODS[2]] = p_randomization(rk, draw_stratified(rk, psk, N_RAND, RNG), Mk, yk)
        obs_p[METHODS[3]] = p_randomization(rk, draw_crt(psk, N_RAND, RNG), Mk, yk)

        # ---- calibration: labels drawn from the propensity, outcomes untouched
        # so outcome and recurrence are confounded through architecture but
        # conditionally independent given it.
        hits = {m: 0 for m in METHODS}
        n_ok = {m: 0 for m in METHODS}
        for _ in range(N_NULL):
            rn = (RNG.random(psk.size) < psk).astype(float)
            if rn.sum() < 4 or (1 - rn).sum() < 4:
                continue
            pv = {
                METHODS[0]: p_hc3(rn, Zk, yk)[0],
                METHODS[1]: p_matched(rn, Zk, yk, RNG),
                METHODS[2]: p_randomization(rn, draw_stratified(rn, psk, N_RAND, RNG), Mk, yk),
                METHODS[3]: p_randomization(rn, draw_crt(psk, N_RAND, RNG), Mk, yk),
            }
            for m, v in pv.items():
                if np.isfinite(v):
                    n_ok[m] += 1
                    hits[m] += int(v < ALPHA)

        # ---- power: same design, plus the observed effect planted on top
        phits = {m: 0 for m in METHODS}
        pn = {m: 0 for m in METHODS}
        for _ in range(N_POWER):
            rn = (RNG.random(psk.size) < psk).astype(float)
            if rn.sum() < 4 or (1 - rn).sum() < 4:
                continue
            yp = yk + obs_coef * rn
            pv = {
                METHODS[0]: p_hc3(rn, Zk, yp)[0],
                METHODS[1]: p_matched(rn, Zk, yp, RNG),
                METHODS[2]: p_randomization(rn, draw_stratified(rn, psk, N_RAND, RNG), Mk, yp),
                METHODS[3]: p_randomization(rn, draw_crt(psk, N_RAND, RNG), Mk, yp),
            }
            for m, v in pv.items():
                if np.isfinite(v):
                    pn[m] += 1
                    phits[m] += int(v < ALPHA)

        for m in METHODS:
            t1 = hits[m] / n_ok[m] if n_ok[m] else np.nan
            pw = phits[m] / pn[m] if pn[m] else np.nan
            rows.append(dict(outcome=label, method=m, observed_p=obs_p[m],
                             type1_error=t1, n_null=n_ok[m],
                             power=pw, n_power=pn[m],
                             planted_effect=obs_coef))
            print(f"  {label[:38]:40s} {m:44s} "
                  f"type I {t1:.3f}   power {pw:.3f}   observed p {obs_p[m]:.4f}")

    out = pd.DataFrame(rows)
    out.to_csv(OUT_TSV, sep="\t", index=False)
    print(f"\nWrote {OUT_TSV}")
    make_figure(out)
    return out


def make_figure(res):
    outcomes = list(dict.fromkeys(res["outcome"]))
    fig, axes = plt.subplots(1, 2, figsize=(17.5, 5.6))
    ypos = np.arange(len(METHODS))[::-1]
    marks = ["o", "s", "^"]

    ax = axes[0]
    for k, oc in enumerate(outcomes):
        sub = res[res.outcome == oc].set_index("method")
        ax.plot([sub.loc[m, "type1_error"] for m in METHODS], ypos,
                marks[k], ms=13, mfc="black", mec="black", ls="none",
                label=oc)
    ax.axvline(ALPHA, color="black", ls=(0, (5, 5)), lw=1.6)
    ax.set_yticks(ypos)
    ax.set_yticklabels(METHODS, fontsize=14)
    ax.set_xlabel("false positive rate when recurrence carries no information\n"
                  "beyond architecture  (nominal 0.05, dashed)", fontsize=15)
    ax.set_xlim(0, max(0.12, res["type1_error"].max() * 1.15))
    ax.tick_params(labelsize=13)

    ax = axes[1]
    for k, oc in enumerate(outcomes):
        sub = res[res.outcome == oc].set_index("method")
        ax.plot([sub.loc[m, "power"] for m in METHODS], ypos,
                marks[k], ms=13, mfc="black", mec="black", ls="none",
                label=oc)
    ax.set_yticks(ypos)
    ax.set_yticklabels([])
    ax.set_xlabel("power against the observed effect", fontsize=15)
    ax.set_xlim(0, 1)
    ax.tick_params(labelsize=13)
    ax.legend(frameon=False, fontsize=12, loc="lower right")

    for a in axes:
        for sp in ("top", "right"):
            a.spines[sp].set_visible(False)
        a.tick_params(axis="y", length=0)
    fig.tight_layout()
    fig.savefig(OUT_PDF, bbox_inches="tight")
    fig.savefig(os.path.splitext(OUT_PDF)[0] + ".png", dpi=200, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {OUT_PDF}")


if __name__ == "__main__":
    run()
